apiVersion: v1
kind: List
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: standard
    provisioner: pd.csi.storage.gke.io
    parameters:
      type: pd-standard
    allowVolumeExpansion: true
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer

  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: balanced
    provisioner: pd.csi.storage.gke.io
    parameters:
      type: pd-balanced
    allowVolumeExpansion: true
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer

  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: ssd
    provisioner: pd.csi.storage.gke.io
    parameters:
      type: pd-ssd
    allowVolumeExpansion: true
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer

  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: extreme
    provisioner: pd.csi.storage.gke.io
    parameters:
      type: pd-extreme
      # Minimum required disk space for iops = 10000 value in extreme disks is 84GB
      # Under this disk size it will not work
      # Calculation formula = 0.6 x Disk GB =< IOPS value >= 120 x Disk GB
      provisioned-iops-on-create: "10000"
    allowVolumeExpansion: true
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer

  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: regional-standard
    provisioner: pd.csi.storage.gke.io
    parameters:
      type: pd-standard
      replication-type: regional-pd
    allowVolumeExpansion: true
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer

  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: regional-ssd
    provisioner: pd.csi.storage.gke.io
    parameters:
      type: pd-ssd
      replication-type: regional-pd
    allowVolumeExpansion: true
    reclaimPolicy: Retain
    volumeBindingMode: WaitForFirstConsumer
